# Generated by Django 5.0.2 on 2024-03-11 17:28

import CalisthenicsWorkoutTracker.meals.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), CalisthenicsWorkoutTracker.meals.validators.validate_meal_name], verbose_name='Meal Name')),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000)], verbose_name='Calories')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('meal_type', models.CharField(choices=[('Soup', 'Soup'), ('Main', 'Main'), ('Dessert', 'Dessert'), ('Drink', 'Drink')], max_length=20, verbose_name='Meal Type')),
                ('meal_name_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20, verbose_name='Meal Name Type')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('carbohydrates', models.PositiveIntegerField(blank=True, null=True, verbose_name='Carbohydrates')),
                ('proteins', models.PositiveIntegerField(blank=True, null=True, verbose_name='Proteins')),
                ('fats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Fats')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal_plans.mealplan', verbose_name='MealPlan')),
            ],
        ),
    ]
