# Generated by Django 5.0.2 on 2024-03-11 17:28

import CalisthenicsWorkoutTracker.meal_plans.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), CalisthenicsWorkoutTracker.meal_plans.validators.validate_meal_plan_name], verbose_name='Meal Plan Name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('meal_plan_type', models.CharField(choices=[('Bulk', 'Bulk'), ('Cut', 'Cut'), ('Other', 'Other')], max_length=15, verbose_name='Meal Plan Type')),
                ('goal_calories', models.PositiveIntegerField(help_text='Goal calories/day', validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(4000)], verbose_name='Goal Calories')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
    ]
