# Generated by Django 5.0.2 on 2024-03-11 17:28

import CalisthenicsWorkoutTracker.programs.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3), CalisthenicsWorkoutTracker.programs.validators.validate_program_name], verbose_name='Program Name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
            ],
        ),
    ]
